name: flutter_http_cache
description: HTTP caching library for Flutter applications
version: 0.1.0
# repository: https://github.com/umairkhancis/flutter_http_cache

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  crypto: ^3.0.3
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.14
  synchronized: ^3.1.0
  dio: ^5.3.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
